# -*- coding: utf-8 -*-
"""M31.08 - conditional_logic_drills.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WN_71VbgWmVuX1hjOpPooQW89SXy1o_Q

## 1:  `take_umbrella`

Write a function called `take_umbrella` that takes two arguments: a string representing the current weather and a float representing the chance of rain today.

Your function should return `True` or `False` based on the following criteria.

You should take an umbrella if it's currently raining or if it's cloudy and the chance of rain is over 0.20.
You shouldn't take an umbrella if it's sunny unless it's more likely to rain than not.
The options for the current weather are sunny, cloudy, and rainy.

For example, `take_umbrella('sunny', 0.40)` should return `False`.

As an additional challenge, consider solving this kata using only logical operaters and not using any if statements.
"""

def take_umbrella(weather, rain_chance):
    """
    tells you if you should bring an umbrella given some weather data

    Args:
        weather: the current weather. Valid choices are sunny, cloudy, and rainy
        rain_chance: float of the chance of rain. 0.5 -> 50% chance to rain

    Returns:
        True/False on if you should bring an umbrella today
    """
    
    # your code here
    if weather == "sunny" and rain_chance < 0.20:
      return "No need for an umbrella today!"
    elif weather == "sunny" and rain_chance > 0.20:
      return "Bring an umbrella today."

    elif weather == "cloudy" and rain_chance <0.20:
      return "No need for an umbrella today!"
    elif weather == "cloudy" and rain_chance > 0.20:
      return "Bring an umbrella today."

    elif weather == "rainy" and rain_chance < 0.20: 
      return "No need for an umbrella today!"
    elif weather == "rainy" and rain_chance > 0.20: 
      return "Bring an umbrella today."

take_umbrella("sunny", 0.4)

"""## 2: `color probability`

You're playing a game with a friend involving a bag of marbles. In the bag are ten marbles:

- 1 smooth red marble
- 4 bumpy red marbles
- 2 bumpy yellow marbles
- 1 smooth yellow marble
- 1 bumpy green marble
- 1 smooth green marble

You can see that the probability of picking a smooth red marble from the bag is 1 / 10 or 0.10 and the probability of picking a bumpy yellow marble is 2 / 10 or 0.20.

The game works like this: your friend puts her hand in the bag, chooses a marble (without looking at it) and tells you whether it's bumpy or smooth. Then you have to guess which color it is before she pulls it out and reveals whether you're correct or not.

You know that the information about whether the marble is bumpy or smooth changes the probability of what color it is, and you want some help with your guesses.

Write a function `color_probability` that takes two arguments: a color ('red', 'yellow', or 'green') and a texture ('bumpy' or 'smooth') and returns the probability of drawing that combination as a decimal fraction accurate to two places.

The probability should be a string and should discard any digits after the 100ths place. For example, 2 / 3 or 0.6666666666666666 would become the string '0.66'. Note this is different from rounding.

As a complete example, color_probability('red', 'bumpy') should return the string '0.57'.
"""

def color_probability(color, texture):
    """
    Tells you the probability of picking a particular kind of marble

    Args:
        color: the color of the marble. Choices are 'red', 'yellow', or 'green'.
        texture: the texture of the marble. Choices are 'bumpy', and 'smooth'.

    Returns:
        probability that you will pick a marble described.
    """
    # use these to calculate your answer
    red_smooth = 1
    red_bumpy = 4
    yellow_bumpy = 2
    yellow_smooth = 1
    green_bumpy = 1
    green_smooth = 1

    # your code here

    if texture == "smooth" and color == "red":
      return str(red_smooth/3)[0:4]
    elif texture == "smooth" and color == "yellow":
      return str(yellow_smooth/3)[0:4]
    elif texture == "smooth" and color == "green":
      return str(green_smooth/3)[0:4]

    if texture == "bumpy" and color == "red": 
      return str(red_bumpy/7)[0:4]
    elif texture == "bumpy" and color == "yellow":
      return str(yellow_bumpy/7)[0:4]
    elif texture == "bumpy" and color == "green":
      return str(green_bumpy/7)[0:4]

color_probability("red", "bumpy")

