# -*- coding: utf-8 -*-
"""M31.05 - Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GmEfEJD_znKGB-qI01g5QLthb-gM2FDt
"""

# 1. The perimeter of a rectangle is measured as 2 * width + 2 * height. 
# Write a function that takes two arguments, width and height, and returns the
# perimeter of the rectangle.

width = 4
height = 7

def perimeter_rectangle(width, height):
  return (2*width)+(2*height)

# 2. Write a function that asks the user to enter their name, then their age. 
# Return a message addressed to them that tells them the year that 
# they will turn 100 years old.

from datetime import datetime
current_year = datetime.now().year

def year_100():
  name = input("Enter your name:")
  age_now = int(input("Enter your age:"))

  age_100 = 100 - age_now

  year_to_100 = current_year + age_100 

  return(name + "You will turn 100 in the year " + str(year_to_100) + ".")

