# -*- coding: utf-8 -*-
"""M31.06 python_strings_drills.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RPuBUwcG9G1LXPlLFf6Yj5gYXYgGCX3k

## 1: Hello world

Create a function called `hello` that takes one argument (`person`, a string) and returns a string saying hello to that person. The result should be formatted so that when you call the function like this:

```python
hello('Moon')
```

you return a string that looks like this:

```python
'Hello, Moon'
```
"""

# your code here

def hello(person):  
  person = str(input("What is your name?"))
  return ('Hello' + person)

"""<br>

## 2: Quotable

1. [Quotable](https://www.codewars.com/kata/thinkful-string-drills-quotable/)

Create a function called `quotable` that takes a person's name as a parameter called `name` and a quote of theirs as a parameter called `quote`, and return a string attributing the quote to the person in the following format:

```
'[name] said: "[quote]"'
```

For example, if name is 'Grae' and 'quote' is 'Practice makes perfect' then your function should return the string

'Grae said: "Practice makes perfect"'
Unfortunately, something is wrong with the instructions in the function body. Your job is to fix it so the function returns correctly formatted quotes.

Be careful with your quotation marks!
"""

def quotable(name, quote):
  name = str(input("Enter your name:"))
  quote = str(input("Say something:"))
  return({}, "said:", {} .format(name, quote))

"""## 3: Jedi name

You just took a contract with the Jedi council. They need you to write a function, greet_jedi(), which takes two arguments (a first name and a last name), works out the corresponding Jedi name, and returns a string greeting the Jedi.

A person's Jedi name is the first three letters of their last name followed by the first two letters of their first name. For example:

```
>>> greet_jedi('Beyonce', 'Knowles')
'Greetings, master KnoBe'
```

Note the capitalization: the first letter of each name is capitalized. Your input may or may not be capitalized. Your function should handle it and return the Jedi name in the correct case no matter what case the input is in:

```
>>> greet_jedi('grae', 'drake')
'Greetings, master DraGr'
```
"""

def greet_jedi(first_name, last_name):
  first_name = str(input("Enter your first name:"))
  last_name = str(input("Enter your last name:"))
  
  n_last_name = str(last_name[1:3].capitalize)
  n_first_name = str(first_name[1:2].capitalize)
  master_name = str('_'.join([n_last_name, n_first_name]))

  return("Greetings, master {}".format(master_name))

first_name = str(input("Enter your first name:"))
  last_name = str(input("Enter your last name:"))
  
  n_last_name = str(last_name[1:3].capitalize)
  n_first_name = str(first_name[1:2].capitalize)
  master_name = str('_'.join([n_last_name, n_first_name]))

  print("Greetings, master {}".format(master_name))

"""## 4: Poem formatter

You have a collection of lovely poems. Unfortuantely they aren't formatted very well. They're all on one line, like this:

```
Beautiful is better than ugly. Explicit is better than implicit. Simple is better than complex. Complex is better than complicated.
```

What you want is to present each sentence on a new line, so that it looks like this:

```
Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
```

Write a function called `format_poem` that takes a string like the one-line example as an argument and returns a new string that is formatted across multiple lines with each new sentence starting on a new line when you print it out.

Hint: You may find the `str.split()` and the `str.join()` string methods to be helpful.

Every sentence will end with a period, and every new sentence will have one space before the previous period. Be careful about trailing whitespace in your solution.
"""

# No function
print("Beautiful is better than ugly.\nExplicit is better than implicit. \nSimple is better than complex. \nComplex is better than complicated.")

def format_poem(one_line_poem):
  one_line_poem = str("Beautiful is better than ugly. Explicit is better than implicit. Simple is better than complex. Complex is better than complicated.")
  split_poem = str.join(one_line_poem.split("."\n))

  return(split_poem)

