# -*- coding: utf-8 -*-
"""M31.10 - python_dictionary_drill_starter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUQbykvAVfQ8AMrs-526wTBRefGSIMto

## 1: `fillable`

You're running an online business and a big part of your day is fulfilling orders. As your volume picks up that's been taking more of your time, and unfortunately lately you've been running into situations where you take an order but can't fulfill it.

You've decided to write a function `fillable` that takes three arguments: a dictionary stock representing all the merchandise you have in stock, a string merch representing the thing your customer wants to buy, and an integer `n` representing the number of units of merch they would like to buy. Your function should return `True` if you have the merchandise in stock to complete the sale, otherwise it should return `False`.

Valid data will always be passed in and n will always be >= 1.
"""

# inventory = {"apples": 0, "grapes":20, "oranges":15}
# inventory = {(fruit:num)}

stock = {"apples": 0, "grapes":20, "oranges":15}

def fillable(stock):
  ask_fruit = str(input("What fruit would you like? "))
  if ask_fruit in stock:
    y = stock[ask_fruit]
    if y >= 1:
      print("True")
    elif y < 1:
      print("False")
  elif ask_fruit not in stock:
    print("We do not have this fruit.")
  return

fillable(stock)

stock = {"apples": 0, "grapes":20, "oranges":15}
customer = []

def fillable(stock, customer):
  ask_fruit = str(input("What fruit would you like? "))
  much_fruit = int(input("How many would you like? "))
  y = [ask_fruit , much_fruit]
  customer.append(y)
  if ask_fruit in stock:
    y = stock[ask_fruit]
    if much_fruit >= 1:
      print("True")
    elif much_fruit < 1:
      print("False")
  elif ask_fruit not in stock:
    print("We do not have this fruit.")
  return

fillable(stock, customer)

"""## 2: user_contacts

You're putting together contact information for all the users of your website to ship them a small gift. You queried your database and got back a list of users, where each user is another list with up to two items: a string representing the user's name and their shipping zip code. Example data might look like:

```python
[["Grae Drake", 98110], ["Bethany Kok"], ["Alex Nussbacher", 94101], ["Darrell Silver", 11201]]
```

Notice that one of the users above has a name but doesn't have a zip code.

Write a function `user_contacts` that takes a two-dimensional list like the one above and returns a dictionary with an item for each user where the key is the user's name and the value is the user's zip code. If your data doesn't include a zip code then the value should be `None`.

For example, using the input above, user_contacts would return this dictionary:

```python
{
    "Grae Drake": 98110,
    "Bethany Kok": None,
    "Alex Nussbacher": 94101,
    "Darrell Silver": 11201,    
}
```

You don't have to worry about leading zeros in zip codes.
"""

name_zip = [["Grae Drake", 98110], ["Bethany Kok"], ["Alex Nussbacher", 94101], ["Darrell Silver", 11201]]
empty_name_zip = []

def user_contacts(name_zip):
  for x in name_zip:
    if len(x) != 2:
      x.append(None)
    empty_name_zip.append(x)
  y = dict(empty_name_zip)
  print(y)
  return

user_contacts(name_zip)

"""**DISREGARD DRAFTS/THOUGHT PROCESSES OF #2**

def user_contacts(name_zip):
  for x in name_zip:
    print(len(x))
      
  return 

user_contacts(name_zip)
"""

