# -*- coding: utf-8 -*-
"""M31.07 python_number_drills.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zpZEigtinW4gpN75VgLLD0IjOTJMw4pU

## 1: Rømer temperature

You're writing an excruciatingly detailed alternate history novel set in a world where [Daniel Gabriel Fahrenheit](https://en.wikipedia.org/wiki/Daniel_Gabriel_Fahrenheit) was never born.

Since Fahrenheit never lived the world kept on using the [Rømer scale](https://en.wikipedia.org/wiki/R%C3%B8mer_scale), invented by fellow Dane [Ole Rømer](https://en.wikipedia.org/wiki/Ole_R%C3%B8mer) to this very day, skipping over the Fahrenheit and Celsius scales entirely.

Your magnum opus contains several thousand references to temperature, but those temperatures are all currently in degrees Celsius. You don't want to convert everything by hand, so you've decided to write a function, `celsius_to_romer` that takes a temperature in degrees Celsius and returns the equivalent temperature in degrees Rømer.

For example: `celsius_to_romer(24)` should return 20.1.
"""

# 1. Romer Temperature

celsius = int(input("What is the temperature in celsius?"))
romer = (celsius * (21/40)) + 7.5

print(romer)

"""## 2: Pixelart planning

You're laying out a rad pixel art mural to paint on your living room wall in homage to [Paul Robertson](http://68.media.tumblr.com/0f55f7f3789a354cfcda7c2a64f501d1/tumblr_o7eq3biK9s1qhccbco1_500.png), your favorite pixel artist.

You want your work to be perfect down to the millimeter. You haven't decided on the dimensions of your piece, how large you want your pixels to be, or which wall you want to use. You just know that you want to fit an exact number of pixels.

To help decide those things you've decided to write a function, `is_divisible` that will tell you whether a wall of a certain length can exactly fit an integer number of pixels of a certain length.

Your function should take two arguments: the size of the wall in millimeters and the size of a pixel in millimeters. It should return `Tru`e if you can fit an exact number of pixels on the wall, otherwise it should return `False`. For example `is_divisible(4050, 27)` should return `True`, but `is_divisible(4066, 27)` should return `False`.

Note: you don't need to use an `if` statement here. Remember that in Python an expression using the `==` comparison operator will evaluate to either `True` or `False`:

```
>>> def equals_three(num):
>>>     return num == 3
>>> equals_three(5)
False
>>> equals_three(3)
True
```
"""

# 2. Pixelart Planning
# If num1 was divisible by num2, its remainder would be 0, hence use modulo %
# (Q): Everything is divisible by 1, so why is it FALSE if I did FLOAT/1 ?

def is_divisible(size_wall, size_pixel):
  size_wall%size_pixel == 0 
  print(size_wall%size_pixel == 0)
  return 

is_divisible(20, 1)

"""## 3: Blue and red marbles

You and a friend have decided to play a game to drill your statistical intuitions. The game works like this:

You have a bunch of red and blue marbles. To start the game you grab a handful of marbles of each color and put them into the bag, keeping track of how many of each color go in. You take turns reaching into the bag, guessing a color, and then pulling one marble out. You get a point if you guessed correctly. The trick is you only have three seconds to make your guess, so you have to think quickly.

You've decided to write a function, `guess_blue` to help automatically calculate whether you should guess blue or red. The function should take four arguments:

- the number of blue marbles you put in the bag to start
- the number of red marbles you put in the bag to start
- the number of blue marbles pulled out so far, and
- the number of red marbles pulled out so far.

`guess_blue` should return the probability of drawing a blue marble, expressed as a float. For example, guess_blue(5, 5, 2, 3) should return 0.6.
"""

# 3. Blue and Red Marbles

def guess_blue(num_blue_start, num_red_start, num_blue_out, num_red_out):
  probability_blue = num_blue_out/num_blue_start
  probability_red = num_red_out/num_red_start
  print("blue =", probability_blue)
  return 

guess_blue(5, 5, 2, 3)

# 3. Version 2

def guess_blue(num_blue_start, num_red_start, num_blue_out, num_red_out):
  probability_blue = num_blue_out/num_blue_start
  probability_red = num_red_out/num_red_start
  print("blue =", probability_blue, "\nred =", probability_red) 
  if probability_blue > probability_red: 
      print("Choose Blue") 
  else: print("Choose Red")
  return 

guess_blue(9, 9, 7, 4)

"""## 4: Congo pizza

Your company, [Congo Pizza](http://interesting-africa-facts.com/Africa-Landforms/Congo-Rainforest-Facts.html), is the second-largest online frozen pizza retailer. You own a number of international warehouses that you use to store your frozen pizzas, and you need to figure out how many crates of pizzas you can store at each location.

Congo recently standardized its storage containers: all pizzas fit inside a cubic crate, 16-inchs on a side. The crates are super tough so you can stack them as high as you want.

Write a function `box_capacity` that figures out how many crates you can store in a given warehouse. The function should take three arguments: the length, width, and height of your warehouse (in feet) and should return an integer representing the number of boxes you can store in that space.

For example: a warehouse 32 feet long, 64 feet wide, and 16 feet high can hold 13,824 boxes because you can fit 24 boxes across, 48 boxes deep, and 12 boxes high, so `box_capacity(32, 64, 16)` should return 13824.
"""

# 4. Congo Pizza

def box_capacity(wh_length, wh_width, wh_height):
  # Enter warehouse dimensions in feet
  boxes_across = int(wh_length/(16/12))
  boxes_deep = int(wh_width/(16/12))
  boxes_high = int(wh_height/(16/12)) 
  return print(boxes_across * boxes_deep * boxes_high)

box_capacity(32, 64, 16)

